version: '3.8'

services:
  # For production scalability, use the distributed mode by uncommenting and configuring the following:
  # minio1, minio2, minio3, minio4 services and updating the command to use all 4 nodes
  # Example: server http://minio{1...4}/data{1...2}
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "${MINIO_SERVER_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ${MINIO_VOLUME}:/data
      - ./init:/init
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    deploy:
      resources:
        limits:
          memory: "3G"
        reservations:
          memory: "1G"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        sh /init/setup.sh;
        exit 0;
      "
    volumes:
      - ./init:/init
      - ./mc-config:/root/.mc
    env_file:
      - .env

volumes:
  minio_data:
